### ISSUE TITLE
Run maven-build-tools in profile

### ISSUE THREAD

**Issue by vertti** [lkoskela/maven-build-utils#1]
It should be possible to run this tool only in specific build profile. For example in my current project the output from this tool is over five pages long and so I want it displayed only when I enable for example `mvn -P buildtime` profile.

Unfortunately `<extensions>` is not allowed under `profiles/profile/build` so we need some other way of specifying in which profiles we want to enable this. Suggestions?

**Comment by lkoskela** [comment]
This was closed with pull request [#2](https://github.com/lkoskela/maven-build-utils/pull/2)
